### ISSUE TITLE
系统类的category +load没有hook到

### ISSUE THREAD

**Issue by Litt1er** [bukuzao/bukuzao#2]
您好   我试了下示例代码  发现系统类的category load方法没有hook到（NSObject UIView 等） 请教下这是什么原因呢

**Comment by everettjf** [comment]
系统的动态库加载要早于 hook的动态库，在hook之前就已经执行完了。

**Comment by Litt1er** [comment]
这边用MachOView看了app可执行文件  自定义的动态库是在Foundation前面加载的

**Comment by everettjf** [comment]
是的。搞不定。。。

**Comment by tripleCC** [comment]
@everettjf @Litt1er 可以hook到，参考https://github.com/tripleCC/Laboratory/tree/master/HookLoadMethods

@everettjf 大佬你的应该是依赖了 Foundation / UIKit 框架，导致 Foundation / UIKit 中的 +load 先执行了，只要把依赖去掉就没问题，实际执行就合 MachOView 的顺序一致了

**Comment by tripleCC** [comment]
@everettjf 大佬， objc_copyClassNamesForImage 无法获得自定义 image 里面的 NSObject UIView 等分类对应的类，这些分类所属的类定义在 
Foundation / UIKit image 里面，可以直接读取 no lazy Section 解决这个问题

@Litt1er 可以参考 https://github.com/tripleCC/Laboratory/blob/master/HookLoadMethods/A4LoadMeasure/A4LoadMeasure.m
